### ISSUE TITLE
Showing Vlcode not initialize. Error (e.replace is not a function).

### ISSUE THREAD

**Issue by balrick** [Codeneos/vlocode#385]
![image](https://user-images.githubusercontent.com/755687/187545775-c389bafc-b047-4883-9b47-8df9dc9bf802.png)

TypeError: e.replace is not a function
    at String.replaceAll (userPath\.vscode\extensions\ms-python.python-2022.12.1\out\client\extension.js:2:154691)
    at Proxy.applyAutoColors (userPath\.vscode\extensions\curlybracket.vlocode-0.17.5\out\vlocode-core.js:1607:14)
    at Proxy.write (userPath\.vscode\extensions\curlybracket.vlocode-0.17.5\out\vlocode-core.js:1594:36)
    at Object.write (userPath\.vscode\extensions\curlybracket.vlocode-0.17.5\out\vlocode.js:4737:60)
    at userPath\.vscode\extensions\curlybracket.vlocode-0.17.5\out\vlocode-core.js:1171:78
    at Array.map (<anonymous>)
    at Object.write (userPath\.vscode\extensions\curlybracket.vlocode-0.17.5\out\vlocode-core.js:1171:57)
    at Logger.writeEntry (userPath\.vscode\extensions\curlybracket.vlocode-0.17.5\out\vlocode-core.js:1234:36)
    at Logger.write (userPath\.vscode\extensions\curlybracket.vlocode-0.17.5\out\vlocode-core.js:1223:14)
    at Logger.log (userPath\.vscode\extensions\curlybracket.vlocode-0.17.5\out\vlocode-core.js:1206:25)
    at Proxy.execute (userPath\.vscode\extensions\curlybracket.vlocode-0.17.5\out\vlocode.js:3806:29)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at CommandExecutor.execute (userPath\.vscode\extensions\curlybracket.vlocode-0.17.5\out\vlocode.js:4974:13)
    at a._executeContributedCommand (userPath\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:85:63914)

<hr/>

<body>
<div tabindex="-1" class="console-message-wrapper console-from-api console-error-level console-selected" style="box-sizing: border-box; min-width: 0px; min-height: 0px; display: flex; border-top-width: ; border-top-style: ; border-top-color: var(--override-error-border-color); border-bottom: 1px solid transparent; --console-color-black:#000; --console-color-red:rgb(237 78 76); --console-color-green:rgb(1 200 1); --console-color-yellow:rgb(210 192 87); --console-color-blue:rgb(39 116 240); --console-color-magenta:rgb(161 66 244); --console-color-cyan:rgb(18 181 203); --console-color-gray:rgb(207 208 208); --console-color-darkgray:rgb(137 137 137); --console-color-lightred:rgb(242 139 130); --console-color-lightgreen:rgb(161 247 181); --console-color-lightyellow:rgb(221 251 85); --console-color-lightblue:rgb(102 157 246); --console-color-ightmagenta:#f5f; --console-color-lightcyan:rgb(132 240 255); --console-color-white:#fff; background-color: var(--override-console-error-background-color); --console-color-lightmagenta:rgb(214 112 214);"><div class="console-message" style="box-sizing: border-box; min-width: 0px; min-height: 17px; clear: right; position: relative; padding: 3px 22px 1px 0px; margin-left: 24px; flex: 1 1 auto; display: flex;"><div class="console-message-stack-trace-toggle" style="box-sizing: border-box; min-width: 0px; min-height: 0px; flex: 1 1 auto; display: flex; flex-direction: row; align-items: flex-start;"><div class="console-message-stack-trace-wrapper" aria-label="workbench.desktop.main.js:sourcemap:86 [Extension Host] Error: Vlocode is not initialized; VlocityDatapackService is null
    at VlocodeService.get datapackService [as datapackService] (userPath\.vscode\extensions\curlybracket.vlocode-0.17.5\out\vlocode.js:6656:19)
    at Object.get (userPath\.vscode\extensions\curlybracket.vlocode-0.17.5\out\vlocode-core.js:417:44)
    at Object.get (userPath\.vscode\extensions\curlybracket.vlocode-0.17.5\out\vlocode-util.js:1493:33)
    at Proxy.validateSalesforceConnectivity (userPath\.vscode\extensions\curlybracket.vlocode-0.17.5\out\vlocode.js:6979:25)
    at Proxy.validate (userPath\.vscode\extensions\curlybracket.vlocode-0.17.5\out\vlocode.js:1275:32)
    at CommandExecutor.execute (userPath\.vscode\extensions\curlybracket.vlocode-0.17.5\out\vlocode.js:4972:36)
    at a._executeContributedCommand (userPath\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:85:63922)
    at a.$executeContributedCommand (userPath\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:85:64626)
    at o._doInvokeHandler (userPath\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:95:13691)
    at o._invokeHandler (userPath\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:95:13373)
    at o._receiveRequest (userPath\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:95:12143)
    at o._receiveOneMessage (userPath\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:95:10845)
    at userPath\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:95:8952
    at w.invoke (userPath\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:61:145)
    at b.deliver (userPath\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:61:2266)
    at p.fire (userPath\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:61:1844)
    at c.fire (userPath\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:69:19006)
    at userPath\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:111:17079
    at w.invoke (userPath\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:61:145)
    at b.deliver (userPath\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:61:2266)
    at p.fire (userPath\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:61:1844)
    at c.fire (userPath\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:69:19006)
    at i._receiveMessage (userPath\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:69:23593)
    at userPath\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:69:21127
    at w.invoke (userPath\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:61:145)
    at b.deliver (userPath\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:61:2266)
    at p.fire (userPath\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:61:1844)
    at p.acceptChunk (userPath\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:69:15837)
    at userPath\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:69:14967
    at Socket.l (userPath\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:69:26303)
    at Socket.emit (node:events:390:28)
    at Socket.emit (node:domain:475:12)
    at addChunk (node:internal/streams/readable:315:12)
    at readableAddChunk (node:internal/streams/readable:289:9)
    at Socket.Readable.push (node:internal/streams/readable:228:10)
    at Pipe.onStreamRead (node:internal/stream_base_commons:199:23) Stack table expanded" style="box-sizing: border-box; min-width: 0px; min-height: 0px; flex: 1 1 auto; display: flex; flex-direction: column; align-items: stretch;"><div aria-expanded="true" tabindex="-1" style="box-sizing: border-box; min-width: 0px; min-height: 0px; outline-width: 0px; flex: 0 0 auto;"><span class="source-code" style="box-sizing: border-box; min-width: 0px; min-height: 0px; font-family: var(--source-code-font-family); white-space: pre-wrap; font-size: var(--source-code-font-size) !important; line-height: 1.2;"><span class="console-message-text" style="box-sizing: border-box; min-width: 0px; min-height: 0px; color: var(--override-error-text-color) !important;"><span style="box-sizing: border-box; min-width: 0px; min-height: 0px; contain: paint; display: inline-block; max-width: 100%; color: blue;"> </span>Error: Vlocode is not initialized; VlocityDatapackService is null
    at VlocodeService.get datapackService [as datapackService] (userPath\.vscode\extensions\curlybracket.vlocode-0.17.5\out\vlocode.js:6656:19)
    at Object.get (userPath\.vscode\extensions\curlybracket.vlocode-0.17.5\out\vlocode-core.js:417:44)
    at Object.get (userPath\.vscode\extensions\curlybracket.vlocode-0.17.5\out\vlocode-util.js:1493:33)
    at Proxy.validateSalesforceConnectivity (userPath\.vscode\extensions\curlybracket.vlocode-0.17.5\out\vlocode.js:6979:25)
    at Proxy.validate (userPath\.vscode\extensions\curlybracket.vlocode-0.17.5\out\vlocode.js:1275:32)
    at CommandExecutor.execute (userPath\.vscode\extensions\curlybracket.vlocode-0.17.5\out\vlocode.js:4972:36)
    at a._executeContributedCommand (userPath\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:85:63922)
    at a.$executeContributedCommand (userPath\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:85:64626)
    at o._doInvokeHandler (userPath\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:95:13691)
    at o._invokeHandler (userPath\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:95:13373)
    at o._receiveRequest (userPath\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:95:12143)
    at o._receiveOneMessage (userPath\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:95:10845)
    at userPath\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:95:8952
    at w.invoke (userPath\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:61:145)
    at b.deliver (userPath\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:61:2266)
    at p.fire (userPath\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:61:1844)
    at c.fire (userPath\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:69:19006)
    at userPath\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:111:17079
    at w.invoke (userPath\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:61:145)
    at b.deliver (userPath\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:61:2266)
    at p.fire (userPath\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:61:1844)
    at c.fire (userPath\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:69:19006)
    at i._receiveMessage (userPath\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:69:23593)
    at userPath\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:69:21127
    at w.invoke (userPath\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:61:145)
    at b.deliver (userPath\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:61:2266)
    at p.fire (userPath\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:61:1844)
    at p.acceptChunk (userPath\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:69:15837)
    at userPath\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:69:14967
    at Socket.l (userPath\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:69:26303)
    at Socket.emit (node:events:390:28)
    at Socket.emit (node:domain:475:12)
    at addChunk (node:internal<span class="devtools-link" title="/streams/readable" role="link" tabindex="-1" style="box-sizing: border-box; min-width: 0px; min-height: 0px; color: var(--override-console-link-color); text-decoration: underline; cursor: pointer; word-break: break-all;">/streams/readable:315</span>:12)
    at readableAddChunk (node:internal<span class="devtools-link" title="/streams/readable" role="link" tabindex="-1" style="box-sizing: border-box; min-width: 0px; min-height: 0px; color: var(--override-console-link-color); text-decoration: underline; cursor: pointer; word-break: break-all;">/streams/readable:289</span>:9)
    at Socket.Readable.push (node:internal<span class="devtools-link" title="/streams/readable" role="link" tabindex="-1" style="box-sizing: border-box; min-width: 0px; min-height: 0px; color: var(--override-console-link-color); text-decoration: underline; cursor: pointer; word-break: break-all;">/streams/readable:228</span>:10)
    at Pipe.onStreamRead (node:internal<span class="devtools-link" title="/stream_base_commons" role="link" tabindex="-1" style="box-sizing: border-box; min-width: 0px; min-height: 0px; color: var(--override-console-link-color); text-decoration: underline; cursor: pointer; word-break: break-all;">/stream_base_commons:199</span>:23)</span></span></div><div class="" role="group" style="box-sizing: border-box; min-width: 0px; min-height: 0px; flex: 0 0 auto;"><span class="monospace" style="display: inline-block; --monospace-font-size:12px; --monospace-font-family:consolas,lucida console,courier new,monospace; --source-code-font-size:12px; --source-code-font-family:consolas,lucida console,courier new,monospace; box-sizing: border-box; min-width: 0px; min-height: 0px; font-family: var(--monospace-font-family); font-size: var(--monospace-font-size) !important;">

  | I | @ | console.ts:137
-- | -- | -- | --

</span></div></div></div></div></div><div tabindex="-1" class="console-message-wrapper console-group-title console-from-api console-info-level" style="box-sizing: border-box; min-width: 0px; min-height: 0px; display: flex; border-top-width: ; border-top-style: ; border-top-color: var(--override-error-border-color); border-bottom: 1px solid transparent; --console-color-black:#000; --console-color-red:rgb(237 78 76); --console-color-green:rgb(1 200 1); --console-color-yellow:rgb(210 192 87); --console-color-blue:rgb(39 116 240); --console-color-magenta:rgb(161 66 244); --console-color-cyan:rgb(18 181 203); --console-color-gray:rgb(207 208 208); --console-color-darkgray:rgb(137 137 137); --console-color-lightred:rgb(242 139 130); --console-color-lightgreen:rgb(161 247 181); --console-color-lightyellow:rgb(221 251 85); --console-color-lightblue:rgb(102 157 246); --console-color-ightmagenta:#f5f; --console-color-lightcyan:rgb(132 240 255); --console-color-white:#fff; font-weight: 700; --console-color-lightmagenta:rgb(214 112 214);"><span is="ui-icon" class="expand-group-icon spritesheet-smallicons smallicon-triangle-down icon-mask" style="box-sizing: border-box; min-width: 0px; min-height: 0px; display: inline-block; flex: 0 0 auto; user-select: none; position: relative; left: 10px; top: 5px; margin-right: 2px; --override-icon-mask-background-color:rgb(145 145 145); background-color: var(--override-icon-mask-background-color); -webkit-mask-position: var(--spritesheet-position); -webkit-mask-image: var(--image-file-smallIcons); color: rgb(232, 234, 237); font-family: consolas, &quot;lucida console&quot;, &quot;courier new&quot;, monospace; font-size: 12px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 700; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial; --spritesheet-position:-80px 30px; width: 10px; height: 10px;"></span><div class="console-message" tabindex="-1" style="box-sizing: border-box; min-width: 0px; min-height: 17px; clear: right; position: relative; padding: 3px 22px 1px 0px; margin-left: 12px; flex: 1 1 auto; display: flex; color: rgb(232, 234, 237); font-family: consolas, &quot;lucida console&quot;, &quot;courier new&quot;, monospace; font-size: 12px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 700; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(32, 33, 36); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><span class="source-code" style="box-sizing: border-box; min-width: 0px; min-height: 0px; font-family: var(--source-code-font-family); white-space: pre-wrap; font-size: var(--source-code-font-size) !important; flex: 1 1 auto; line-height: 1.2;"><br class="Apple-interchange-newline">
</body>
</html>
<html>

**Comment by Codeneos** [comment]
Thanks for your bug report! Based on your stack trace the error occurs in a different extension `ms-python.python` which is the python extension for vscode. I checked their source code and it indeed replaces the standard string `string.replaceAll` function with a custom function that cannot handle a `RegExp` object which is supported by the NodeJS default method. 

The issue can be resolved by disabling the Python Extension; meanwhile I will check if I can use `replace` instead of `replaceAll` with a different Regex. And will ask on the github of the Phyton extension why they override String.prototype functions as this is bad practice.

**Comment by balrick** [comment]
Disabling the Python Extension does fix the issue at the moment. Please let me know if there is anything else I can help with.

**Comment by Codeneos** [comment]
For now I changed `replaceAll` to `replace` see PR #386; I'll it directly with as release 0.17.6 which should be available in about 30-min from VSCode's Marketplace

**Comment by Codeneos** [comment]
@balrick let me know if the fix is working properly for you - if it is I will close this issues as resolved
