### ISSUE TITLE
Content version is throwing error 

### ISSUE THREAD

**Issue by irfanlai** [Codeneos/vlocode#399]
**VSCode:**
Version: 1.76.2 (user setup)
Electron: 19.1.11
Chromium: 102.0.5005.196
Node.js: 16.14.2
V8: 10.2.154.26-electron.0
OS: Windows_NT x64 10.0.22621
Sandboxed: Yes

**Vlocode:**
v0.18.18

We are trying to download and deploy DocumentTemplate and we are getting missing ContentVersion info so when we are trying to browse the content of \DATAPACKS\ContentVersion\ using vlocode, we are getting the following error.

```
[15:22:36.068] [SalesforceConnection] [error] Error: 
Title, vlocity_cmt__GlobalKey__c, Name from ContentVersion where vlocity_cmt__GlobalKey__c
                                  ^
ERROR at Row:1:Column:46
No such column 'Name' on entity 'ContentVersion'. If you are attempting to use a custom field, be sure to append the '__c' after the custom field name. Please reference your WSDL or the describe call for the appropriate names.
        at module.exports.getResponseError (c:\Users\irfan.shaikh\.vscode\extensions\curlybracket.vlocode-0.18.18\out\vlocode.js:18454:20)
        at module.exports.executeRequest (c:\Users\irfan.shaikh\.vscode\extensions\curlybracket.vlocode-0.18.18\out\vlocode.js:18430:24)
        at process.processTicksAndRejections (node:internal/process/task_queues:96:5)
        at async module.exports.request (c:\Users\irfan.shaikh\.vscode\extensions\curlybracket.vlocode-0.18.18\out\vlocode.js:18368:24)
[15:22:36.069] [SalesforceConnection] [debug] --- Query error ---

```

If we try to export the data pack under it we get 0 data packs exported message.

https://user-images.githubusercontent.com/48936344/228070690-dbf400ab-4bbc-4829-8a6b-be1e12785e28.mp4

**Comment by irfanlai** [comment]
Closing as this is a non-issue.

**Comment by Codeneos** [comment]
Thanks for bringing this to my attention! In version 0.19 there is support for exporting more datapack types. Fields that are selected in the datapack explorer will be validate against the target org to avoid field `No such column` errors.
